Repository arfc/pride, pull requests merged in 2020-12, with the labels that each got.

#109 Temoa
  .gitignore
  README.md
  requirements.txt
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/01_uiuc.sql
  temoa-uiuc/data_files/02_uiuc.sql
  temoa-uiuc/data_files/03_uiuc.sql
  temoa-uiuc/data_files/04_uiuc.sql
  temoa-uiuc/data_files/bau_uiuc.sql
  temoa-uiuc/data_parser.py
Labels: Comp:Build, Difficulty:2-Challenging, Priority:1-Critical, Status:5-In Review, Type:Bug

#110 Transportation
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/05_uiuc.sql
  temoa-uiuc/data_files/run_scenario05.txt
  temoa-uiuc/data_parser.py
Labels: Comp:Build, Difficulty:1-Beginner, Priority:2-Normal, Status:1-New, Type:Feature

#112 Temoa: Expands transportation sector, specific nuclear turbine
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/06_uiuc.sql
  temoa-uiuc/data_files/07_uiuc.sql
  temoa-uiuc/data_files/run_scenario06.txt
  temoa-uiuc/data_files/run_scenario07.txt
  temoa-uiuc/data_parser.py
Labels: Comp:Build, Difficulty:1-Beginner, Priority:1-Critical, Status:5-In Review, Type:Feature

#115 added electric vehicles to the temoa's model
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/08_uiuc.sql
  temoa-uiuc/data_files/run_scenario08.txt
Labels: Comp:Input, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review

#117 adds a transportation/vehicle sector to the data parser
  temoa-uiuc/Snakefile
  temoa-uiuc/data_parser.py
  temoa-uiuc/plot_capacity.py
  temoa-uiuc/plot_emissions.py
Labels: Comp:Analysis, Difficulty:2-Challenging, Priority:1-Critical, Status:5-In Review, Type:Feature

#119 Adds Hydrogen to the uiuc's model
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/09_uiuc.sql
  temoa-uiuc/data_files/run_scenario09.txt
  temoa-uiuc/data_parser.py
Labels: Comp:Input, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review

#122 Adds investment cost, lifetime, and e-waste of transportation sector
  fuel-analysis/README.md
  fuel-analysis/microR.ipynb
  fuel-analysis/temoa-model.ipynb
  temoa-uiuc/data_files/09_uiuc.sql
Labels: Comp:Input, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review

#129 Corrected energy equivalence for the transportation sector
  fuel-analysis/temoa-model.ipynb
  temoa-uiuc/data_files/09_uiuc.sql
Labels: Comp:Input, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Bug

#130 Adding Chilled Water System (CHWS) to Temoa's model
  data_processing/cws_power.ipynb
  data_processing/energy-storage.md
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/10_uiuc.sql
  temoa-uiuc/data_files/run_scenario10.txt
  temoa-uiuc/data_parser.py
  temoa-uiuc/temoa-uiuc-chws.md
Labels: Comp:Core, Comp:Input, Difficulty:2-Challenging, Priority:2-Normal, Status:4-In Progress, Type:Question
