Repository arfc/pride, pull requests merged in 2021-01, with the labels that each got.

#134 Created scenario 11 incorporating fixed costs
  data_processing/automobile_data_scraping.ipynb
  data_processing/fixed_cost_assumptions.md
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/11_uiuc.sql
  temoa-uiuc/data_files/run_scenario11.txt
Labels: Comp:Input, Difficulty:2-Challenging, Priority:1-Critical, Status:4-In Progress, Type:Feature

#133 Adds geothermal technology to TEMOA's model
  data_processing/energy-storage.md
  data_processing/geothermal.ipynb
  temoa-uiuc/data_files/11_uiuc.sql
  temoa-uiuc/data_parser.py
  temoa-uiuc/temoa-uiuc-chws.md
Labels: Comp:Core, Comp:Input, Comp:Output, Difficulty:2-Challenging, Priority:2-Normal, Status:5-In Review

#138 Updates fuel consumption in Temoa's model
  data_processing/fuel-analysis.ipynb
  fuel-analysis/2019grossfueldata.csv
  fuel-analysis/README.md
  fuel-analysis/microR.ipynb
  temoa-uiuc/data_files/11_uiuc.sql
Labels: Comp:Input, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review

#142 fixed ELCVCL and H2VCL efficiencies
  temoa-uiuc/data_files/10_uiuc.sql
Labels: Comp:Input, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Bug

#148 Added scenario 12 with land-use requirements
  data_processing/geothermal.ipynb
  data_processing/landuse.md
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/12_uiuc.sql
  temoa-uiuc/data_files/run_scenario12.txt
  temoa-uiuc/optimal_sizing.ipynb
Labels: Comp:Core, Difficulty:1-Beginner, Priority:1-Critical, Status:4-In Progress, Type:Feature
