Repository arfc/pride, pull requests merged in 2021-02, with the labels that each got.

#152 Updated CWS and GEOT given the new data
  data_processing/cws_power.ipynb
  data_processing/geothermal.ipynb
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/13_uiuc.sql
  temoa-uiuc/data_files/run_scenario13.txt
  temoa-uiuc/data_parser.py
Labels: Comp:Input, Difficulty:1-Beginner, Priority:1-Critical, Status:5-In Review, Type:Bug

#149 2050 extend
  data_processing/automobile_data_scraping.ipynb
  data_processing/cws_power.ipynb
  data_processing/fixed_cost_assumptions.md
  data_processing/geothermal.ipynb
  data_processing/ghg_emissions.ipynb
  data_processing/landuse.md
  temoa-uiuc/Snakefile
  temoa-uiuc/data_files/14_uiuc.sql
  temoa-uiuc/data_files/UIUC_2050_cost.sql
  temoa-uiuc/data_files/UIUC_2050_land.sql
  temoa-uiuc/data_files/run_cost_scenario.txt
  temoa-uiuc/data_files/run_land_scenario.txt
  temoa-uiuc/data_files/run_scenario14.txt
  temoa-uiuc/data_parser.py
Labels: Priority:1-Critical, Status:4-In Progress

#157 added instructions to run Temoa
  README.md
Labels: Comp:Build, Difficulty:1-Beginner, Priority:4-Low, Status:5-In Review, Type:Docs
